feat: update usage instructions and add options for model and temperature in the commit message generator script

diff --git a/ai-commit-message/ai-commit-message b/ai-commit-message/ai-commit-message
--- a/ai-commit-message/ai-commit-message
+++ b/ai-commit-message/ai-commit-message
@@ -1,13 +1,15 @@
-#!/bin/sh -eu
+#!/bin/bash -eu
 
 usage() {
   echo "Usage: ai-commit-message [OPTIONS]"
   echo ""
   echo "Generate git commit message from staged diff using GhatGPT."
   echo "Options:"
-  echo "  -k,--api-key API_KEY    OpenAI API key (default: \$OPENAI_API_KEY environment variable)"
-  echo "  -l,--lang LANG          Language for output (default: \$LANG environment variable else en-US)"
-  echo "  -b,--body-lines NUMBER  Add number of bullet points for body (default: 0)"
+  echo "  -k,--api-key API_KEY    OpenAI API key (default: \$OPENAI_API_KEY environmental variable)"
+  echo "  -m,--model MODEL        OpenAI model (default: gpt-4o-mini)"
+  echo "  -t,--temperature TEMP   OpenAI Temperature for sampling (default: 0.7)"
+  echo "  -l,--lang LANG          Language for output (default: \$LANG environmental variable else en-US)"
+  echo "  -b,--body-lines NUMBER  Number of lines for body (default: 0 = none)"
   echo "  -n,--non-interactive    Do not prompt for confirmation (default: no)"
   echo "  -h,--help               Show this help message"
 }
@@ -31,6 +33,14 @@ while [ $# -gt 0 ]; do
     -k|--api-key)
       OPENAI_API_KEY=$2
       shift 2;
+      ;;
+    -m|--model)
+      OPTION_MODEL=$2
+      shift 2
+      ;;
+    -t|--temperature)
+      OPTION_TEMPERATURE=$2
+      shift 2
       ;;
     -l|--lang)
       OPTION_LANG=$2
@@ -56,15 +66,14 @@ while [ $# -gt 0 ]; do
   esac
 done
 
-if [ -z "$OPENAI_API_KEY" ]; then
-  echo "OpenAI API key is required. Please set OPENAI_API_KEY environment variable or use -k option." >&2
+if [ -z "${OPENAI_API_KEY:-}" ]; then
+  echo "OpenAI_API_key is required. Please set OPENAI_API_KEY environmental variable or use -k option." >&2
   exit 1
 fi
-
 PROMPT_LANG="output must be in lang: ${OPTION_LANG:-${LANG:-en-US}}"
 
 PROMPT_BODY=""
-if [ ! -z "$OPTION_BODY_LINES" ]; then
+if [ ! -z "${OPTION_BODY_LINES:-}" ]; then
   PROMPT_BODY="add description, in under ${OPTION_BODY_LINES} bullet points, open empty line before description."
 fi
 
@@ -92,7 +101,7 @@ ${PROMPT_BODY}
 ${GIT_DIFF}
 --
 EOL
-  )
+)
 
   QUERY=$(jq -n --arg content "$PROMPT" '{"role": "user", "content": $content}')
 
@@ -101,13 +110,13 @@ EOL
   ANSWER=$(curl https://api.openai.com/v1/chat/completions -s \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer ${OPENAI_API_KEY}" \
-    -d "{\"model\": \"gpt-3.5-turbo\", 
-         \"temperature\": 0.5,
+    -d "{\"model\": \"${OPTION_MODEL:-gpt-4o-mini}\",
+         \"temperature\": ${OPTION_TEMPERATURE:-0.7},
          \"max_tokens\": 1000,
          \"messages\": [${QUERY}]}")
 
-  if [ -z "$ANSWER" ]; then
-    echo "Failed to generate commit message. Please try again." >&2
+  if [ -z "${ANSWER:-}" ]; then
+    echo "Failed to get response from OpenAI API." >&2
     exit 1
   fi
 
